# Site settings
title: Search Engagement for Crypto Startups
tag_text: Biscuit
description: MintSignals is a search-focused team that helps crypto startups become easier to find.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
